name: CI Github Pages
on:
  #监听push操作
  push:
    branches:
      - master
jobs:
  # 任务ID
  build-and-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 官方action，将代码拉取到虚拟机
      - name: Checkout  ️ 
        uses: actions/checkout@v3
        uses: actions/setup-node@v2
        with:
          node-version: 16.19.0
          cache: 'npm'

      - name: Install and Build   # 安装依赖、打包，如果提前已打包好无需这一步
        run: |
          cd src/web
          npm install
          npm run build:gh-pages

      - name: Deploy   # 部署
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # 部署后提交到那个分支
          folder: src/web/dist # 这里填打包好的目录名称
